import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { ToastContainer } from "react-toastify";
import CategoryList from "@/components/categories/CategoryList";
// import { AuthInit } from "@/components/auth/authInit/authinit";
import TokenInit from "@/shared/token/token";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <AuthInit /> */}
        <TokenInit />
        <div className="container">
          <Header />
          <div className="layout-container">
            <main className="page-content">
              {children}
              <Footer />
            </main>

            <div className="category-list-container">
              <CategoryList />
            </div>
          </div>
          <ToastContainer position="top-right" autoClose={3000} />
        </div>
      </body>
    </html>
  );
}
